# Generated by Django 4.2.23 on 2026-07-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_remove_medicalrecord_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
