# Generated by Django 4.2.23 on 2026-07-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_remove_medicalrecord_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='prescription',
        ),
    ]
