# Generated by Django 4.2.23 on 2026-07-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_remove_medicalrecord_prescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
