# Generated by Django 4.2.23 on 2026-07-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_alter_medicalrecord_options_medicalrecord_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='consultation_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
