# Generated by Django 4.2.23 on 2026-07-13 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0002_remove_medicalrecord_prescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(help_text='e.g. 500mg', max_length=50)),
                ('frequency', models.CharField(help_text='e.g. Twice a day', max_length=50)),
                ('duration', models.CharField(help_text='e.g. 5 days', max_length=50)),
                ('instructions', models.CharField(blank=True, help_text='e.g. After food', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical_records.medicalrecord')),
            ],
        ),
    ]
