# Generated by Django 4.2.23 on 2026-07-21 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_remove_prescription_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['medicine_name']},
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(help_text='Example: 500 mg / 1 Tablet', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in Days'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(choices=[('Once Daily', 'Once Daily'), ('Twice Daily', 'Twice Daily'), ('Three Times Daily', 'Three Times Daily'), ('Every 6 Hours', 'Every 6 Hours'), ('Every 8 Hours', 'Every 8 Hours'), ('SOS', 'SOS')], max_length=30),
        ),
    ]
