# Generated by Django 4.2.23 on 2026-07-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_alter_prescription_options_prescription_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='before_after_food',
            field=models.CharField(choices=[('Before Food', 'Before Food'), ('After Food', 'After Food')], default='After Food', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(choices=[('Once Daily', 'Once Daily'), ('Twice Daily', 'Twice Daily'), ('Three Times Daily', 'Three Times Daily'), ('Every 6 Hours', 'Every 6 Hours'), ('Every 8 Hours', 'Every 8 Hours'), ('SOS', 'SOS')], default='Twice Daily', max_length=30),
        ),
    ]
