# Generated by Django 6.0.7 on 2026-07-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='consultation_mode',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='sms_reminder_sent',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
