# Generated by Django 4.2.23 on 2026-07-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_risk_level_appointment_risk_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-appointment_time']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='distance_from_clinic',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='history_noshow_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prior_noshows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prior_visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sms_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
