# Generated by Django 4.2.23 on 2026-07-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='distance_from_clinic',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='history_noshow_ratio',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='prior_noshows',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='prior_visits',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
