# Generated by Django 4.2.23 on 2026-07-16 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

   dependencies = [
    ('patients', '0002_alter_patient_blood_group_alter_patient_gender'),
    ('hospital', '0002_alter_doctoravailability_day_of_week'),
    ('appointments', '0006_alter_appointment_appointment_time_and_more'),
]

   operations = [
        
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='patients.patient')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
