# Generated by Django 4.2.23 on 2026-07-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_id_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
