# Generated by Django 4.2.23 on 2026-07-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_waitlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
