# Generated by Django 4.2.23 on 2026-07-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctoravailability_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Dermatologist', 'Dermatologist'), ('Pediatrician', 'Pediatrician'), ('Gynecologist', 'Gynecologist'), ('ENT Specialist', 'ENT Specialist'), ('Ophthalmologist', 'Ophthalmologist'), ('Psychiatrist', 'Psychiatrist')], max_length=100),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
