# Generated by Django 4.2.23 on 2026-07-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_department_id_alter_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('General Physician', 'General Physician'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Dermatologist', 'Dermatologist'), ('Pediatrician', 'Pediatrician'), ('Gynecologist', 'Gynecologist'), ('ENT Specialist', 'ENT Specialist'), ('Ophthalmologist', 'Ophthalmologist'), ('Psychiatrist', 'Psychiatrist')], max_length=100),
        ),
    ]
