# Generated by Django 4.2.23 on 2026-07-17 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_doctorleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('EMERGENCY', 'Emergency'), ('LEAVE', 'Leave')], default='AVAILABLE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_status', to='hospital.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('EMERGENCY', 'Emergency'), ('LEAVE', 'Leave')], default='ABSENT', max_length=20)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hospital.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'attendance_date')},
            },
        ),
    ]
