# Generated by Django 4.2.23 on 2026-07-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_doctorstatus_doctorattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorstatus',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('EMERGENCY', 'Emergency'), ('ON_LEAVE', 'On Leave')], default='AVAILABLE', max_length=20),
        ),
    ]
