# Generated by Django 4.2.23 on 2026-07-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_doctorstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorstatus',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('EMERGENCY', 'Emergency'), ('ON_LEAVE', 'On Leave'), ('NOT_AVAILABLE', 'Not Available')], default='AVAILABLE', max_length=20),
        ),
    ]
