# Generated by Django 4.2.23 on 2026-07-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Appointment', 'Appointment'), ('Prescription', 'Prescription'), ('Billing', 'Billing'), ('Payment', 'Payment'), ('Reminder', 'Reminder'), ('System', 'System')], default='System', max_length=30),
        ),
    ]
